const KEY='ramPortfolioCMS_v3',SESSION='ramPortfolioAdminPassword_v2';
/* Credentials are verified server-side via /api/login */
const clone=v=>JSON.parse(JSON.stringify(v));
function loadData(){const base=clone(DEFAULT_PORTFOLIO);let saved=null;for(const key of [KEY,'ramPortfolioCMS_v2','ramPortfolioCMS_v1']){try{saved=JSON.parse(localStorage.getItem(key));if(saved)break}catch{}}if(!saved)return base;return{...base,...saved,settings:{...base.settings,...(saved.settings||{})},profile:{...base.profile,...(saved.profile||{})},stats:saved.stats||base.stats,projects:saved.projects||base.projects,reels:saved.reels||base.reels,brochures:saved.brochures||base.brochures,logos:saved.logos||base.logos,services:saved.services||base.services}}
let data=loadData();
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
async function save(){try{$('#saveState').textContent='Saving…';const r=await fetch('/api/data',{method:'POST',headers:{'Content-Type':'application/json','Authorization':'Bearer '+(sessionStorage.getItem(SESSION)||'')},body:JSON.stringify(data)});if(r.status===401){sessionStorage.removeItem(SESSION);alert('Session expired or server restarted. Please log in again.');location.reload();return}if(!r.ok)throw new Error('Save failed');localStorage.setItem(KEY,JSON.stringify(data));try{new BroadcastChannel('ram-portfolio-updates').postMessage('refresh')}catch{}$('#saveState').textContent='Saved permanently · '+new Date().toLocaleTimeString();renderAll()}catch(err){alert('Save failed: '+err.message)}}
async function migrateInlineMedia(){let changed=false;for(const r of data.reels||[]){if(r.video&&r.video.startsWith('data:')){const blob=await(await fetch(r.video)).blob();r.video=await MediaDB.put(blob);changed=true}}for(const b of data.brochures||[]){if(b.pdf&&b.pdf.startsWith('data:')){const blob=await(await fetch(b.pdf)).blob();b.pdf=await MediaDB.put(blob);changed=true}}if(changed){try{localStorage.setItem(KEY,JSON.stringify(data))}catch{}}}
async function recoverLegacyUploads(local,server){let recovered=0;async function blobFrom(ref){if(!ref)return null;if(ref.startsWith('idb://')){const item=await MediaDB.get(ref);return item?.blob||null}if(ref.startsWith('data:'))return await(await fetch(ref)).blob();return null}async function recoverCollection(key,field,kind){for(const item of local[key]||[]){const blob=await blobFrom(item[field]||'');if(!blob)continue;let target=(server[key]||[]).find(x=>x.id===item.id);if(!target){target={...item};server[key]=server[key]||[];server[key].push(target)}const ext=blob.type==='application/pdf'?'.pdf':blob.type.includes('png')?'.png':blob.type.includes('webm')?'.webm':'.mp4',file=new File([blob],(item.title||item.name||kind)+ext,{type:blob.type});try{const o=await uploadWithProgress(file,()=>{},{kind,id:item.id,title:item.title||item.name||''});target[field]=o.url;if(item.poster)target.poster=item.poster;if(item.cover)target.cover=item.cover;recovered++}catch(e){console.warn('Legacy recovery failed',item.id,e)}}}await recoverCollection('reels','video','video');await recoverCollection('brochures','pdf','brochure');await recoverCollection('logos','image','logo');return recovered}
async function enter(){
  $('#loginScreen').hidden=true;
  $('#adminApp').hidden=false;
  $('#saveState').textContent='Loading and recovering saved content…';
  const localSnapshot=data;
  let merged=false;
  try{
    const r=await fetch('/api/data',{cache:'no-store'});
    if(r.ok){
      const serverData=await r.json();
      serverData.settings={...DEFAULT_PORTFOLIO.settings,...(serverData.settings||{})};
      serverData.profile={...DEFAULT_PORTFOLIO.profile,...(serverData.profile||{})};
      serverData.stats=serverData.stats||DEFAULT_PORTFOLIO.stats;
      const recovered=await recoverLegacyUploads(localSnapshot,serverData);
      if(recovered)merged=true;
      for(const key of ['projects','reels','brochures','logos','services']){
        serverData[key]=serverData[key]||[];
        for(const item of localSnapshot[key]||[]){
          const existing=serverData[key].find(x=>x.id===item.id);
          if(!existing){serverData[key].push(item);merged=true}
          else if(key==='logos'&&item.image&&!existing.image){existing.image=item.image;existing.watermark=item.watermark;merged=true}
        }
      }
      data=serverData;
    }
  }catch(e){console.warn('Server load failed',e)}
  await migrateInlineMedia();
  if(merged)await fetch('/api/data',{method:'POST',headers:{'Content-Type':'application/json','Authorization':'Bearer '+(sessionStorage.getItem(SESSION)||'')},body:JSON.stringify(data)});
  renderAll();
  $('#saveState').textContent=merged?'Previous uploads recovered and saved':'All existing content loaded';
}
if(sessionStorage.getItem(SESSION))enter();
$('#backPortfolio').onclick=e=>{e.preventDefault();sessionStorage.removeItem(SESSION);location.href='index.html'};$('#logoutAdmin').onclick=()=>{sessionStorage.removeItem(SESSION);location.href='index.html'};
$('#loginForm').onsubmit=async e=>{e.preventDefault();const email=$('#loginEmail').value.trim().toLowerCase(),password=$('#loginPassword').value;try{const r=await fetch('/api/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email,password})});const result=await r.json();if(result.ok){sessionStorage.setItem(SESSION,result.token||'1');$('#loginError').textContent='';enter()}else{$('#loginError').textContent=result.error||'Incorrect email or password.'}}catch{$('#loginError').textContent='Connection failed. Is the server running?'}};
$$('.tab').forEach(b=>b.onclick=()=>{$$('.tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');$$('.panel').forEach(p=>p.classList.remove('active'));$('#'+b.dataset.panel).classList.add('active');$('#panelTitle').textContent=b.textContent});
function field(name,label,value,type='text',full=false){return `<div class="field ${full?'full':''}"><label>${label}</label>${type==='textarea'?`<textarea name="${name}">${value||''}</textarea>`:`<input name="${name}" type="${type}" value="${String(value||'').replace(/"/g,'&quot;')}">`}</div>`}
function renderProfile(){const p=data.profile;$('#profileForm').innerHTML=field('name','Name',p.name)+field('role','Professional title',p.role)+field('eyebrow','Availability line',p.eyebrow,'text',true)+field('tagline','Hero tagline',p.tagline,'textarea',true)+field('bio','About text',p.bio,'textarea',true)+field('location','Location',p.location)+field('image','Profile image path / URL',p.image)+`<div class="field full"><label>Upload profile image</label><input id="profileUpload" type="file" accept="image/*"><img class="media-preview" src="${p.image}"></div>`+field('resumeUrl','Resume URL',p.resumeUrl)+field('email','Email',p.email)+field('phone','Phone / WhatsApp',p.phone)+field('linkedin','LinkedIn URL',p.linkedin)+field('behance','Behance URL',p.behance)+field('instagram','Instagram URL',p.instagram)+`<div class="field full"><button class="admin-button red">Save profile</button></div>`;$('#profileForm').onsubmit=e=>{e.preventDefault();Object.assign(data.profile,Object.fromEntries(new FormData(e.target)));save()};$('#profileUpload').onchange=async e=>{if(e.target.files[0]){data.profile.image=await compress(e.target.files[0]);save()}}}
function renderStats(){$('#statsAdminList').innerHTML=(data.stats||[]).map((s,i)=>`<div class="project-admin"><div class="logo-mark" style="color:var(--accent)">${s.value}</div><div><h3>${s.label}</h3></div><div class="row-actions"><button data-stedit="${i}">Edit</button><button data-stremove="${i}">Remove</button></div></div>`).join('');$$('[data-stedit]').forEach(b=>b.onclick=()=>openStat(Number(b.dataset.stedit)));$$('[data-stremove]').forEach(b=>b.onclick=()=>{if(confirm('Remove stat?')){data.stats.splice(Number(b.dataset.stremove),1);save()}})}
function openStat(index=-1){const f=$('#statForm'),s=index>=0?data.stats[index]:{value:'',label:''};f.hidden=false;f.elements.index.value=index;f.elements.value.value=s.value;f.elements.label.value=s.label;f.scrollIntoView({behavior:'smooth'})}$('#addStat').onclick=()=>openStat();$('#cancelStat').onclick=()=>$('#statForm').hidden=true;$('#statForm').onsubmit=e=>{e.preventDefault();const o=Object.fromEntries(new FormData(e.target)),i=Number(o.index);delete o.index;if(i>=0)data.stats[i]=o;else data.stats.push(o);e.target.hidden=true;save()};
let currentProjectImages = [];

function renderProjectGalleryAdmin() {
  const container = $('#projectGalleryAdmin');
  if (!container) return;
  container.innerHTML = currentProjectImages.map((src, idx) => `
    <div class="gallery-item-admin ${idx === 0 ? 'is-cover' : ''}">
      ${idx === 0 ? '<span class="cover-badge">COVER</span>' : ''}
      <img src="${src}" alt="Work ${idx + 1}">
      <div class="gallery-item-actions">
        ${idx > 0 ? `<button type="button" onclick="setProjectCover(${idx})">Cover</button>` : '<span></span>'}
        <button type="button" onclick="removeProjectImage(${idx})">✕ Delete</button>
      </div>
    </div>
  `).join('');
  
  if ($('#projectForm') && $('#projectForm').elements && $('#projectForm').elements.image) {
    $('#projectForm').elements.image.value = currentProjectImages[0] || '';
  }
}

window.setProjectCover = function(idx) {
  if (idx <= 0 || idx >= currentProjectImages.length) return;
  const item = currentProjectImages.splice(idx, 1)[0];
  currentProjectImages.unshift(item);
  renderProjectGalleryAdmin();
};

window.removeProjectImage = function(idx) {
  if (idx < 0 || idx >= currentProjectImages.length) return;
  currentProjectImages.splice(idx, 1);
  renderProjectGalleryAdmin();
};

function renderProjects(){const list=[...data.projects].sort((a,b)=>a.order-b.order);$('#projectAdminList').innerHTML=list.map(p=>`<div class="project-admin"><img src="${p.image}"><div><h3>${p.title}</h3><p>${p.category} · ${p.year} (${(p.images&&p.images.length)||(p.image?1:0)} images)</p></div><div class="row-actions"><button data-act="up" data-id="${p.id}">↑</button><button data-act="down" data-id="${p.id}">↓</button><button data-act="edit" data-id="${p.id}">Edit</button><button data-act="remove" data-id="${p.id}">Remove</button></div></div>`).join('');$$('[data-act]').forEach(b=>b.onclick=()=>projectAction(b.dataset.act,b.dataset.id))}
function projectAction(act,id){const i=data.projects.findIndex(p=>p.id===id);if(i<0)return;if(act==='remove'){if(confirm('Remove this project?')){data.projects.splice(i,1);save()}return}if(act==='edit'){openProject(data.projects[i]);return}const sorted=[...data.projects].sort((a,b)=>a.order-b.order),si=sorted.findIndex(p=>p.id===id),j=act==='up'?si-1:si+1;if(j<0||j>=sorted.length)return;const t=sorted[si].order;sorted[si].order=sorted[j].order;sorted[j].order=t;save()}
function openProject(p={id:'project-'+Date.now(),order:data.projects.length+1,year:'2026',image:'',featured:false}){const f=$('#projectForm');f.hidden=false;for(const [k,v] of Object.entries(p)){if(f.elements[k]){if(f.elements[k].type==='checkbox')f.elements[k].checked=!!v;else f.elements[k].value=v||''}}currentProjectImages=Array.isArray(p.images)&&p.images.length>0?[...p.images]:(p.image?[p.image]:[]);renderProjectGalleryAdmin();f.scrollIntoView({behavior:'smooth'})}
$('#addProject').onclick=()=>openProject();$('#cancelProject').onclick=()=>$('#projectForm').hidden=true;$('#projectForm').onsubmit=e=>{e.preventDefault();const o=Object.fromEntries(new FormData(e.target));o.order=Number(o.order)||1;o.featured=e.target.featured.checked;o.images=[...currentProjectImages];o.image=currentProjectImages.length>0?currentProjectImages[0]:(o.image||'');const i=data.projects.findIndex(p=>p.id===o.id);if(i>=0)data.projects[i]={...data.projects[i],...o};else data.projects.push(o);e.target.hidden=true;save()};$('#projectImageUpload').onchange=async e=>{const files=e.target.files;if(!files||files.length===0)return;$('#saveState').textContent='Processing images…';for(let idx=0;idx<files.length;idx++){const src=await compress(files[idx]);currentProjectImages.push(src)}renderProjectGalleryAdmin();$('#saveState').textContent='Images added to gallery — save project to publish';e.target.value=''};
function uploadWithProgress(file,onProgress,meta={}){return new Promise((resolve,reject)=>{const xhr=new XMLHttpRequest();xhr.open('POST','/api/upload');xhr.setRequestHeader('X-File-Name',encodeURIComponent(file.name));xhr.setRequestHeader('Content-Type',file.type||'application/octet-stream');xhr.setRequestHeader('Authorization','Bearer '+(sessionStorage.getItem(SESSION)||''));if(meta.kind)xhr.setRequestHeader('X-Media-Kind',meta.kind);if(meta.id)xhr.setRequestHeader('X-Item-Id',encodeURIComponent(meta.id));if(meta.title)xhr.setRequestHeader('X-Item-Title',encodeURIComponent(meta.title));xhr.upload.onprogress=e=>{if(e.lengthComputable)onProgress(Math.round(e.loaded/e.total*100))};xhr.onload=()=>{try{const o=JSON.parse(xhr.responseText);if(xhr.status>=200&&xhr.status<300&&o.ok)resolve(o);else if(xhr.status===401){sessionStorage.removeItem(SESSION);alert('Session expired or server restarted. Please log in again.');location.reload();reject(new Error('Session expired. Please log in again.'))}else reject(new Error(o.error||'Upload failed'))}catch{reject(new Error('Invalid server response'))}};xhr.onerror=()=>reject(new Error('Network upload failed'));xhr.send(file)})}
function renderReels(){const items=[...(data.reels||[])].sort((a,b)=>a.order-b.order);$('#reelAdminList').innerHTML=items.map(r=>`<div class="project-admin"><video data-video-ref="${r.video}" muted></video><div><h3>${r.title}</h3><p>${r.category} · ${r.year}</p></div><div class="row-actions"><button data-redit="${r.id}">Edit</button><button data-rremove="${r.id}">Remove</button></div></div>`).join('');$$('[data-video-ref]').forEach(async v=>v.src=await MediaDB.url(v.dataset.videoRef));$$('[data-redit]').forEach(b=>b.onclick=()=>openReel(items.find(x=>x.id===b.dataset.redit)));$$('[data-rremove]').forEach(b=>b.onclick=async()=>{if(confirm('Remove reel?')){const item=data.reels.find(x=>x.id===b.dataset.rremove);if(item)await MediaDB.remove(item.video);data.reels=data.reels.filter(x=>x.id!==b.dataset.rremove);save()}})}
function openReel(r={id:'reel-'+Date.now(),title:'New Video',category:'Motion',year:'2026',order:(data.reels||[]).length+1,video:'',poster:'',description:''}){const f=$('#reelForm');f.hidden=false;for(const [k,v] of Object.entries(r))if(f.elements[k])f.elements[k].value=v||'';f.scrollIntoView({behavior:'smooth'})}$('#addReel').onclick=()=>openReel();$('#cancelReel').onclick=()=>$('#reelForm').hidden=true;$('#reelForm').onsubmit=e=>{e.preventDefault();const o=Object.fromEntries(new FormData(e.target));o.order=Number(o.order)||1;data.reels=data.reels||[];const i=data.reels.findIndex(x=>x.id===o.id);if(i>=0)data.reels[i]=o;else data.reels.push(o);e.target.hidden=true;save()};$('#reelPosterUpload').onchange=async e=>{const f=e.target.files[0];if(!f)return;$('#reelForm').elements.poster.value=await compress(f);$('#saveState').textContent='Poster ready — video save hone par publish hoga'};$('#reelVideoUpload').onchange=async e=>{const f=e.target.files[0];if(!f)return;if(f.size>300*1024*1024)return alert('Maximum 300 MB video use karo.');const box=$('#videoUploadProgress'),bar=box.querySelector('i'),msg=box.querySelector('span'),posterPromise=makeVideoPoster(f);bar.style.width='0%';msg.textContent='Uploading 0%';$('#saveState').textContent='Uploading video…';try{const o=await uploadWithProgress(f,p=>{bar.style.width=p+'%';msg.textContent='Uploading '+p+'%'},{kind:'video',id:$('#reelForm').elements.id.value,title:$('#reelForm').elements.title.value});$('#reelForm').elements.video.value=o.url;const titleField=$('#reelForm').elements.title;if(!titleField.value||/^New (Video|Reel)$/i.test(titleField.value))titleField.value=f.name.replace(/\.[^.]+$/,'').replace(/[-_]+/g,' ');if(!$('#reelForm').elements.poster.value)$('#reelForm').elements.poster.value=await posterPromise;bar.style.width='100%';msg.textContent='Upload complete — saving video…';$('#saveState').textContent='Video uploaded — auto-saving…';$('#reelForm').requestSubmit()}catch(err){bar.style.width='0%';msg.textContent='Upload failed';alert(err.message)}};
function renderBrochures(){const items=[...(data.brochures||[])].sort((a,b)=>a.order-b.order);$('#brochureAdminList').innerHTML=items.map(b=>`<div class="project-admin"><img src="${b.cover||'assets/editorial.jpg'}"><div><h3>${b.title}</h3><p>${b.category} · ${b.year}</p></div><div class="row-actions"><button data-bedit="${b.id}">Edit</button><button data-bremove="${b.id}">Remove</button></div></div>`).join('');$$('[data-bedit]').forEach(x=>x.onclick=()=>openBrochure(items.find(b=>b.id===x.dataset.bedit)));$$('[data-bremove]').forEach(x=>x.onclick=async()=>{if(confirm('Remove brochure?')){const item=data.brochures.find(b=>b.id===x.dataset.bremove);if(item)await MediaDB.remove(item.pdf);data.brochures=data.brochures.filter(b=>b.id!==x.dataset.bremove);save()}})}
function openBrochure(b={id:'brochure-'+Date.now(),title:'New Brochure',category:'PDF Brochure',year:'2026',order:(data.brochures||[]).length+1,pdf:'',cover:'',description:''}){const f=$('#brochureForm');f.hidden=false;for(const [k,v] of Object.entries(b))if(f.elements[k])f.elements[k].value=v||'';f.scrollIntoView({behavior:'smooth'})}$('#addBrochure').onclick=()=>openBrochure();$('#cancelBrochure').onclick=()=>$('#brochureForm').hidden=true;$('#brochureForm').onsubmit=e=>{e.preventDefault();const o=Object.fromEntries(new FormData(e.target));o.order=Number(o.order)||1;data.brochures=data.brochures||[];const i=data.brochures.findIndex(x=>x.id===o.id);if(i>=0)data.brochures[i]=o;else data.brochures.push(o);e.target.hidden=true;save()};$('#brochurePdfUpload').onchange=async e=>{const f=e.target.files[0];if(!f)return;if(f.size>300*1024*1024)return alert('Maximum 300 MB brochure use karo.');const box=$('#pdfUploadProgress'),bar=box.querySelector('i'),msg=box.querySelector('span');bar.style.width='0%';msg.textContent='Uploading 0%';$('#saveState').textContent='Uploading PDF…';try{const o=await uploadWithProgress(f,p=>{bar.style.width=p+'%';msg.textContent='Uploading '+p+'%'},{kind:'brochure',id:$('#brochureForm').elements.id.value,title:$('#brochureForm').elements.title.value});$('#brochureForm').elements.pdf.value=o.url;const title=$('#brochureForm').elements.title;if(!title.value||/^New Brochure$/i.test(title.value))title.value=f.name.replace(/\.[^.]+$/,'').replace(/[-_]+/g,' ');bar.style.width='100%';msg.textContent='Upload complete — saving brochure…';$('#saveState').textContent='PDF uploaded — auto-saving…';$('#brochureForm').requestSubmit()}catch(err){bar.style.width='0%';msg.textContent='Upload failed';alert(err.message)}};
function renderLogos(){const logos=[...(data.logos||[])].sort((a,b)=>a.order-b.order);$('#logoAdminList').innerHTML=logos.map(l=>`<div class="project-admin"><div class="logo-mark mark-${l.mark||'letter'} ${l.image?'has-image':''}" style="--logo-color:${l.color||'#151411'}">${l.image?`<img src="${l.image}" alt="${l.name}">`:''}</div><div><h3>${l.name}</h3><p>${l.subtitle}</p></div><div class="row-actions"><button data-ledit="${l.id}">Edit</button><button data-lremove="${l.id}">Remove</button></div></div>`).join('');$$('[data-ledit]').forEach(b=>b.onclick=()=>openLogo(logos.find(x=>x.id===b.dataset.ledit)));$$('[data-lremove]').forEach(b=>b.onclick=()=>{if(confirm('Remove this logo?')){data.logos=data.logos.filter(x=>x.id!==b.dataset.lremove);save()}})}
function openLogo(l={id:'logo-'+Date.now(),name:'NEW LOGO',subtitle:'Category',color:'#e91f2a',mark:'letter',order:(data.logos||[]).length+1,image:'',watermark:false}){const f=$('#logoForm');f.hidden=false;for(const [k,v] of Object.entries(l))if(f.elements[k]){if(f.elements[k].type==='checkbox')f.elements[k].checked=!!v;else f.elements[k].value=v||''}$('#logoImagePreview').src=l.image||'';f.scrollIntoView({behavior:'smooth'})}
$('#addLogo').onclick=()=>openLogo();$('#cancelLogo').onclick=()=>$('#logoForm').hidden=true;$('#logoForm').onsubmit=e=>{e.preventDefault();const o=Object.fromEntries(new FormData(e.target));o.order=Number(o.order)||1;o.watermark=e.target.watermark.checked;data.logos=data.logos||[];if(o.watermark)data.logos.forEach(l=>l.watermark=false);const i=data.logos.findIndex(l=>l.id===o.id);if(i>=0)data.logos[i]=o;else data.logos.push(o);e.target.hidden=true;save()};$('#logoImageUpload').onchange=async e=>{const f=e.target.files[0];if(!f)return;$('#saveState').textContent='Uploading logo…';try{const o=await uploadWithProgress(f,p=>$('#saveState').textContent='Uploading logo '+p+'%',{kind:'logo',id:$('#logoForm').elements.id.value,title:$('#logoForm').elements.name.value});$('#logoForm').elements.image.value=o.url;$('#logoImagePreview').src=o.url;$('#saveState').textContent='Logo uploaded — auto-saving…';$('#logoForm').requestSubmit()}catch(err){alert(err.message)}}
function renderServices(){ $('#serviceAdminList').innerHTML=data.services.map(s=>`<div class="project-admin"><div></div><div><h3>${s.title}</h3><p>${s.description}</p></div><div class="row-actions"><button data-sedit="${s.id}">Edit</button><button data-sremove="${s.id}">Remove</button></div></div>`).join('');$$('[data-sedit]').forEach(b=>b.onclick=()=>openService(data.services.find(x=>x.id===b.dataset.sedit)));$$('[data-sremove]').forEach(b=>b.onclick=()=>{if(confirm('Remove service?')){data.services=data.services.filter(x=>x.id!==b.dataset.sremove);save()}})}
function openService(s={id:'service-'+Date.now(),title:'',description:''}){const f=$('#serviceForm');f.hidden=false;f.elements.id.value=s.id;f.elements.title.value=s.title;f.elements.description.value=s.description;f.scrollIntoView({behavior:'smooth'})}$('#addService').onclick=()=>openService();$('#cancelService').onclick=()=>$('#serviceForm').hidden=true;$('#serviceForm').onsubmit=e=>{e.preventDefault();const o=Object.fromEntries(new FormData(e.target)),i=data.services.findIndex(s=>s.id===o.id);if(i>=0)data.services[i]=o;else data.services.push(o);e.target.hidden=true;save()};
function renderSettings(){const s=data.settings;$('#settingsForm').innerHTML=field('siteTitle','Browser title',s.siteTitle)+field('accent','Accent color',s.accent,'color')+field('background','Background color',s.background,'color')+field('workEyebrow','Work section label',s.workEyebrow)+field('workTitle','Work section title',s.workTitle)+field('mediaEyebrow','Media section label',s.mediaEyebrow)+field('mediaTitle','Media section title',s.mediaTitle)+field('logoEyebrow','Logo section label',s.logoEyebrow)+field('logoTitle','Logo section title',s.logoTitle)+field('servicesEyebrow','Services section label',s.servicesEyebrow)+field('servicesTitle','Services section title',s.servicesTitle)+field('contactEyebrow','Contact section label',s.contactEyebrow)+field('contactTitle','Contact title',s.contactTitle)+field('contactSubtitle','Contact subtitle',s.contactSubtitle,'textarea',true)+field('footerText','Footer text',s.footerText,'textarea',true)+`<div class="field full"><button class="admin-button red">Save settings</button></div>`;$('#settingsForm').onsubmit=e=>{e.preventDefault();Object.assign(data.settings,Object.fromEntries(new FormData(e.target)));save()}}
function renderDashboard(){$('#dashboardStats').innerHTML=[['Projects',data.projects.length],['Videos',(data.reels||[]).length],['Brochures',(data.brochures||[]).length],['Logos',(data.logos||[]).length]].map(([l,v])=>`<div class="stat"><b>${v}</b><span>${l}</span></div>`).join('');$('#dashboardManage').innerHTML=['profile','stats','projects','reels','brochures','logos','services','theme'].map(x=>`<button class="admin-button ghost" data-open-panel="${x}">Manage ${x}</button>`).join('');$$('[data-open-panel]').forEach(b=>b.onclick=()=>{const tab=document.querySelector(`.tab[data-panel="${b.dataset.openPanel}"]`);if(tab)tab.click()})}
function renderAll(){renderDashboard();renderProfile();renderStats();renderProjects();renderReels();renderBrochures();renderLogos();renderServices();renderSettings()}
async function fileData(file){return new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=reject;r.readAsDataURL(file)})}
function fallbackPoster(name){const c=document.createElement('canvas');c.width=900;c.height=506;const x=c.getContext('2d');x.fillStyle='#151411';x.fillRect(0,0,c.width,c.height);x.fillStyle='#e91f2a';x.beginPath();x.arc(450,225,62,0,Math.PI*2);x.fill();x.fillStyle='#fff';x.font='bold 50px Arial';x.textAlign='center';x.fillText('▶',458,243);x.font='bold 28px Arial';x.fillText((name||'PORTFOLIO VIDEO').replace(/\.[^.]+$/,'').slice(0,42).toUpperCase(),450,340);x.font='bold 15px Arial';x.fillStyle='#e91f2a';x.fillText('RAM PRAKASH ©',450,382);return c.toDataURL('image/jpeg',.84)}
async function makeVideoPoster(file){return new Promise(resolve=>{const v=document.createElement('video'),url=URL.createObjectURL(file);v.muted=true;v.preload='auto';v.playsInline=true;const done=()=>{URL.revokeObjectURL(url)};const fail=()=>{done();resolve(fallbackPoster(file.name))};v.onerror=fail;v.onloadedmetadata=()=>{v.currentTime=Math.min(.7,Math.max(.05,(v.duration||1)*.1))};v.onseeked=()=>{try{const max=900,scale=Math.min(1,max/v.videoWidth),c=document.createElement('canvas');c.width=Math.max(2,Math.round(v.videoWidth*scale));c.height=Math.max(2,Math.round(v.videoHeight*scale));c.getContext('2d').drawImage(v,0,0,c.width,c.height);done();resolve(c.toDataURL('image/jpeg',.82))}catch{fail()}};setTimeout(fail,8000);v.src=url})}
async function compress(file){return new Promise((res,rej)=>{const im=new Image(),url=URL.createObjectURL(file);im.onload=()=>{const max=1600,scale=Math.min(1,max/Math.max(im.width,im.height)),c=document.createElement('canvas');c.width=im.width*scale;c.height=im.height*scale;c.getContext('2d').drawImage(im,0,0,c.width,c.height);URL.revokeObjectURL(url);res(c.toDataURL('image/jpeg',.84))};im.onerror=rej;im.src=url})}
$('#exportJson').onclick=()=>{const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='ram-portfolio-content.json';a.click();URL.revokeObjectURL(a.href)};$('#importJson').onchange=e=>{const r=new FileReader();r.onload=()=>{try{data=JSON.parse(r.result);save()}catch{alert('Invalid JSON')}};r.readAsText(e.target.files[0])};$('#resetData').onclick=()=>{if(confirm('Reset all demo changes?')){data=clone(DEFAULT_PORTFOLIO);save()}};